### ISSUE TITLE
Code V1.8

### ISSUE THREAD

**Issue by comradau** [pmos69/dso203_gcc#7]
Hi Pedro,

In between you submitting V1.18 and V1.19 I have revised the code base to make it more readable and to use scope (i.e. use of static, const etc).
I am happy to upload it, but I can't work out how to submit the code revision, and I fear that if I am successful in uploading it could create confusion for others as to which version of code that they should use.
Is there some way I can send you the code base privately on this web site?

Cheers,
Peter Phillipa

**Comment by pmos69** [comment]
Thanks Peter,
I'm away from home because of work this week, but I will try to look
at the code as soon as I can.
I don't have a lot of knowledge about github myself, but I would be
perfectly happy if it would let you just submit the code.
I think there may be an aproval part after that, to allow the code
merger to occur.
Anyway, thanks a lot for your work.

All the best,

Pedro

On Mon, Mar 19, 2012 at 3:52 AM, Peter P
reply@reply.github.com
wrote:

**Comment by comradau** [comment]
Hi Pedro,

I have been unable to work out how to do a submission on github... I think I am blocked from submitting because the web site reports that the repository is read-only. To overcome the problem, I have zipped the source code and attached it to this email - could you make any changes that are needed to bring it up to date with your v1.19, then submit to the repository?

I don't know if you are familiar with the structure of my source code modules? There are reasons why everything is defined as they are in the source code I have sent. I am happy to explain the structure if you would like me to, just let me know.

Regards,
Peter Philippa.

-----Original Message-----

**Comment by pmos69** [comment]
Well, the zip didn't get through, I think.

Anyway, acording to this (http://help.github.com/fork-a-repo/) it seems the correct procedure would be for you to make a fork of this project, make de modifications, and then send me a "pull request"...

**Comment by comradau** [comment]
Hi Pedro,

Ok, I'll give that a try... I'll let you know after it's done.

Peter Philippa

-----Original Message-----
